---
- name: "Ensure Enterprise Repository is disabled"
  replace:
    path: "/etc/apt/sources.list.d/pve-enterprise.list"
    regexp: '^\s*deb {{ enterprise_repository_url }} {{ ansible_distribution_release }} {{ enterprise_repository_distribution }}'
    replace: "# deb {{ enterprise_repository_url }} {{ ansible_distribution_release }} {{ enterprise_repository_distribution }}"
